# docker-compose.yml for LLM_Document_Agent (Gradio version)
# Maintainer: Max

version: '3.9'
services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    restart: always
    volumes:
      - ollama_data:/root/.ollama

  gradio:
    build: .
    container_name: llm_gradio
    ports:
      - "7860:7860"
    environment:
      - OLLAMA_HOST=ollama
    depends_on:
      - ollama
    command: python app/gradio_ui.py

volumes:
  ollama_data:
